services:
  - type: web
    name: cs-matchmaking
    env: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
